import { StyleSheet, Dimensions, Platform } from 'react-native';

export const SIDEBAR_WIDTH = Dimensions.get('window').width * 0.78;

export const C = {
  bg1:        '#DDD0C4',
  bg3:        '#A87A74',
  text:       '#2d1e1c',
  textMuted:  '#6b4e4b',
  textLight:  '#a89290',
  border:     'rgba(168,122,116,0.18)',
  drawerBg:   'rgba(241,227,211,0.98)',
  activeChat: 'rgba(168,122,116,0.16)',
  sendBg:     'rgba(45,30,28,0.12)',
  sendBorder: 'rgba(45,30,28,0.15)',
  danger:     '#c0392b',
};

export const sidebarStyles = StyleSheet.create({
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(45,30,28,0.45)',
  },
  drawer: {
    position: 'absolute',
    top: 0, left: 0, bottom: 0,
    width: SIDEBAR_WIDTH,
    backgroundColor: C.drawerBg,
    paddingTop: 56,
    borderRightWidth: 1,
    borderRightColor: C.border,
    shadowColor: '#2d1e1c',
    shadowOffset: { width: 4, height: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 16,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  drawerHeader: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingBottom: 16,
    borderBottomWidth: 1, borderBottomColor: C.border,
    marginBottom: 12,
  },
  drawerBrand:       { fontSize: 20, fontWeight: '700', color: C.text, letterSpacing: -0.4 },
  newChatBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    marginHorizontal: 16, marginBottom: 20,
    paddingVertical: 13, paddingHorizontal: 18,
    backgroundColor: C.text, borderRadius: 14,
  },
  newChatIcon:  { color: 'white', fontSize: 18, fontWeight: '300' },
  newChatText:  { color: 'white', fontSize: 15, fontWeight: '600', letterSpacing: -0.2 },
  listHeading: {
    fontSize: 11, fontWeight: '700', color: C.textLight,
    letterSpacing: 0.8, textTransform: 'uppercase',
    paddingHorizontal: 20, marginBottom: 4,
  },
  loadingBox: { paddingTop: 32, alignItems: 'center' },
  emptyText:  { color: C.textMuted, fontSize: 14, textAlign: 'center', paddingTop: 32, paddingHorizontal: 24 },
  chatItem: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: 20, paddingVertical: 13,
    borderBottomWidth: 1, borderBottomColor: 'rgba(168,122,116,0.08)',
  },
  chatItemActive: { backgroundColor: C.activeChat },
  chatItemInner:  { flex: 1 },
  chatItemTitle:  { fontSize: 14, fontWeight: '500', color: C.text, marginBottom: 2 },
  chatItemTime:   { fontSize: 12, color: C.textLight },
  chatItemDot:    { width: 7, height: 7, borderRadius: 4, backgroundColor: C.bg3, marginLeft: 8 },

  // ── Search bar ────────────────────────────────────────────────────────────
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(168,122,116,0.10)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    gap: 8,
  },
  searchIcon:  { fontSize: 14 },
  searchInput: { flex: 1, fontSize: 14, color: C.text, paddingVertical: 0 },
  searchClear: { fontSize: 12, color: C.textLight, fontWeight: '600' },

  // ── Profile footer ────────────────────────────────────────────────────────
  profileFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 16,
    marginBottom: 24,
    borderTopWidth: 1,
    borderTopColor: C.border,
  },
  profileAvatar:     { width: 34, height: 34, borderRadius: 17, backgroundColor: C.bg3, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  profileAvatarText: { color: 'white', fontWeight: '700', fontSize: 14 },
  profileEmail:      { flex: 1, fontSize: 14, fontWeight: '500', color: C.text },
});

export const supportSheetStyles = StyleSheet.create({
  kvWrapper:  { position: 'absolute', bottom: 0, left: 0, right: 0 },
  backdrop:   { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(45,30,28,0.45)' },
  sheet: {
    position: 'absolute', bottom: 0, left: 0, right: 0,
    backgroundColor: '#FDFAF7',
    borderTopLeftRadius: 28, borderTopRightRadius: 28,
    padding: 28, paddingBottom: Platform.OS === 'ios' ? 40 : 28,
    shadowColor: '#2d1e1c', shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.10, shadowRadius: 20, elevation: 16,
  },
  closeBtn: {
    position: 'absolute', top: 16, right: 16,
    width: 32, height: 32, borderRadius: 8,
    backgroundColor: 'rgba(168,122,116,0.12)',
    alignItems: 'center', justifyContent: 'center',
  },
  closeBtnText:      { fontSize: 14, color: C.textMuted, fontWeight: '600' },
  title:             { fontSize: 20, fontWeight: '700', color: C.text, marginBottom: 8, marginTop: 8, paddingRight: 40 },
  subtitle:          { fontSize: 14, color: C.textMuted, lineHeight: 20, marginBottom: 20 },
  stars:             { flexDirection: 'row', gap: 12, backgroundColor: 'rgba(168,122,116,0.08)', borderRadius: 14, padding: 16, marginBottom: 14, justifyContent: 'center' },
  star:              { fontSize: 36, color: 'rgba(168,122,116,0.30)' },
  starFilled:        { color: '#C8860A' },
  textArea:          { backgroundColor: 'rgba(168,122,116,0.08)', borderRadius: 14, padding: 14, fontSize: 15, color: C.text, minHeight: 100, marginBottom: 20 },
  actions:           { flexDirection: 'row', gap: 12 },
  cancelBtn:         { flex: 1, paddingVertical: 14, borderRadius: 28, borderWidth: 1, borderColor: 'rgba(168,122,116,0.28)', alignItems: 'center' },
  cancelBtnText:     { fontSize: 15, fontWeight: '600', color: C.textMuted },
  submitBtn:         { flex: 2, paddingVertical: 14, borderRadius: 28, backgroundColor: C.bg3, alignItems: 'center' },
  submitBtnDisabled: { opacity: 0.45 },
  submitBtnText:     { fontSize: 15, fontWeight: '600', color: 'white' },
  confirmBox:        { alignItems: 'center', paddingTop: 16, paddingBottom: 8, gap: 12 },
  confirmEmoji:      { fontSize: 48 },
  confirmTitle:      { fontSize: 20, fontWeight: '700', color: C.text, textAlign: 'center' },
  confirmSub:        { fontSize: 14, color: C.textMuted, textAlign: 'center', lineHeight: 20 },
});

export const profileStyles = StyleSheet.create({
  panel: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: C.drawerBg,
    paddingTop: 56,
  },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingBottom: 16,
    borderBottomWidth: 1, borderBottomColor: C.border,
    marginBottom: 8,
  },
  backBtn:     { width: 36, alignItems: 'flex-start' },
  backBtnText: { fontSize: 26, color: C.text, lineHeight: 30 },
  headerTitle: { fontSize: 17, fontWeight: '600', color: C.text, letterSpacing: -0.3 },
  section:      { paddingHorizontal: 20, marginBottom: 4 },
  sectionLabel: {
    fontSize: 11, fontWeight: '700', color: C.textLight,
    letterSpacing: 0.8, textTransform: 'uppercase',
    marginTop: 20, marginBottom: 6,
  },
  row: {
    flexDirection: 'row', alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1, borderBottomColor: 'rgba(168,122,116,0.10)',
    gap: 12,
  },
  rowIcon:    { fontSize: 16, width: 24, textAlign: 'center' },
  rowLabel:   { flex: 1, fontSize: 15, color: C.text, fontWeight: '500' },
  rowValue:   { fontSize: 13, color: C.textMuted, maxWidth: 140, textAlign: 'right' },
  rowChevron: { fontSize: 18, color: C.textLight, marginLeft: 4 },
  signOutWrapper: {
    marginTop: 'auto',
    paddingHorizontal: 20, paddingTop: 24, paddingBottom: 32,
    borderTopWidth: 1, borderTopColor: C.border,
  },
  signOutBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    paddingVertical: 14, paddingHorizontal: 20,
    backgroundColor: 'rgba(192,57,43,0.08)',
    borderWidth: 1, borderColor: 'rgba(192,57,43,0.18)',
    borderRadius: 12,
  },
  signOutIcon: { fontSize: 16, color: '#c0392b' },
  signOutText: { fontSize: 15, fontWeight: '600', color: '#c0392b' },
});