import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  navbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  navLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  menuBtn: {
    width: 38,
    height: 38,
    justifyContent: 'center',
    gap: 5,
    padding: 4,
  },
  menuLine: {
    width: 22,
    height: 2,
    backgroundColor: '#ffffff',
    borderRadius: 2,
  },
  brand: {
    fontSize: 20,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: 0.5,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#F9D0D8',
    borderWidth: 1,
    borderColor: '#F0C8D0',
  },
  backBtnText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
  },
  dimOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(45,27,32,0.45)',
  },
  sheet: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: width * 0.72,
    backgroundColor: '#643f3f',
    paddingTop: 70,
    paddingBottom: 40,
    paddingHorizontal: 24,
    borderTopRightRadius: 28,
    borderBottomRightRadius: 28,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  sheetBrand: {
    fontSize: 24,
    fontWeight: '800',
    color: '#E8637A',
    letterSpacing: 0.5,
  },
  closeBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(240, 172, 182, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeBtnText: {
    color: '#E8637A',
    fontSize: 13,
    fontWeight: '700',
  },
  sheetTitle: {
    fontSize: 10,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.30)',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 14,
    marginTop: 28,
  },
  sheetLinks: {
    gap: 8,
  },
  sheetLink: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: 'rgba(232,99,122,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(232,99,122,0.12)',
  },
  sheetLinkText: {
    color: 'rgba(255,255,255,0.88)',
    fontSize: 15,
    fontWeight: '600',
  },
  dropdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 1,
  },
  dropdownArrow: {
    color: '#E8637A',
    fontSize: 12,
  },
  dropdownChildren: {
    overflow: 'hidden',
    marginTop: 4,
  },
  dropdownChild: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 44,
    paddingLeft: 8,
  },
  dropdownIndent: {
    width: 2,
    height: 18,
    backgroundColor: 'rgba(232,99,122,0.30)',
    borderRadius: 1,
    marginRight: 12,
    marginLeft: 8,
  },
  dropdownChildText: {
    color: 'rgba(255,255,255,0.60)',
    fontSize: 14,
    fontWeight: '400',
  },
});