// Design tokens — single source of truth for all visual values in the app.
//
// TO UPDATE: change values here only. Do not hardcode colours in components.
//
// FUTURE: auto-generated from tokens/tokens.json via scripts/build-tokens.js
// When that pipeline is ready, do not edit this file manually.

// ── Core palette (light mode) ─────────────────────────────────────────────────

export const colors = {
  // Brand
  primary:     '#A87A74',

  // Text
  text:        '#2D1E1C',
  textMuted:   '#6B4E4B',
  textLight:   '#A89290',

  // Backgrounds
  bgBase:        '#DDD0C4',
  bgGlass:       'rgba(241, 227, 211, 0.60)',
  bgGlassStrong: 'rgba(241, 227, 211, 0.80)',
  bgWarm:        'rgba(241, 227, 211, 0.95)',
  bgPanel:       'rgba(241, 227, 211, 0.98)',  // profile/sidebar panels
  bgSheet:       'rgba(241, 227, 211, 0.97)',  // bottom sheets
  bgModal:       '#FDFAF7',                    // picker and delete modals
  bgDisclaimer:  '#FAF8F4',                    // disclaimer modal card

  // Borders
  border:        'rgba(168, 122, 116, 0.28)',
  borderCard:    'rgba(168, 122, 116, 0.22)',
  borderFocus:   'rgba(168, 122, 116, 0.55)',
  borderError:   'rgba(192, 57, 43, 0.30)',
  borderSuccess: 'rgba(39, 127, 82, 0.30)',

  // Inputs
  inputBg: 'rgba(241, 227, 211, 0.55)',

  // Buttons
  btnPrimary:        '#2D1E1C',
  btnPrimaryPressC1: '#C9A29D',
  btnPrimaryPressC2: '#A87A74',

  // Overlays / backdrops
  backdrop:      'rgba(45, 30, 28, 0.45)',
  backdropModal: 'rgba(45, 30, 28, 0.50)',

  // Semantic
  error:       '#A0291C',
  errorBg:     'rgba(192, 57, 43, 0.08)',
  errorBorder: 'rgba(192, 57, 43, 0.18)',
  errorStrong: 'rgba(192, 57, 43, 0.85)',  // delete confirm button
  success:     '#1E6B44',
  successBg:   'rgba(39, 127, 82, 0.08)',

  // Misc
  white: '#FFFFFF',
};

// ── Dark mode ─────────────────────────────────────────────────────────────────
// Same structure as colors — swap in when isDark is true.

export const darkColors = {
  primary:     '#C8A9A4',

  text:        'rgba(255, 255, 255, 0.90)',
  textMuted:   'rgba(255, 255, 255, 0.55)',
  textLight:   'rgba(255, 255, 255, 0.35)',

  bgBase:        '#1C1917',
  bgGlass:       'rgba(61, 49, 45, 0.85)',
  bgGlassStrong: 'rgba(28, 24, 22, 0.97)',
  bgWarm:        'rgba(221, 208, 196, 0.95)',
  bgPanel:       '#2C1E1A',   // dark sidebar/panel background
  bgSheet:       '#2C1E1A',
  bgModal:       '#2C1E1A',
  bgDisclaimer:  '#2C1E1A',

  border:        'rgba(255, 255, 255, 0.10)',
  borderCard:    'rgba(255, 255, 255, 0.08)',
  borderFocus:   'rgba(200, 169, 164, 0.50)',
  borderError:   'rgba(224, 112, 96, 0.40)',
  borderSuccess: 'rgba(39, 127, 82, 0.35)',

  inputBg: 'rgba(122, 78, 82, 0.35)',

  btnPrimary:        '#C8A9A4',
  btnPrimaryPressC1: '#C9A29D',
  btnPrimaryPressC2: '#A87A74',

  backdrop:      'rgba(0, 0, 0, 0.60)',
  backdropModal: 'rgba(0, 0, 0, 0.70)',

  error:       '#E07060',
  errorBg:     'rgba(224, 112, 96, 0.15)',
  errorBorder: 'rgba(224, 112, 96, 0.30)',
  errorStrong: 'rgba(224, 112, 96, 0.85)',
  success:     '#4CAF82',
  successBg:   'rgba(39, 127, 82, 0.15)',

  white: '#FFFFFF',
};

// ── Crisis banner ─────────────────────────────────────────────────────────────
// Warm amber — serious but not alarming. Avoids red which can cause disengagement.

export const crisisColors = {
  bg:         '#FDF3E3',
  border:     '#E8C882',
  textDark:   '#5C3D0E',
  textMuted:  '#92621A',
  btn:        '#D4860A',
};

// ── Disclaimer modal ──────────────────────────────────────────────────────────

export const disclaimerColors = {
  warning:      '#D97706',      // amber icon
  warningLight: '#FEF3C7',      // amber icon background
  textMuted:    '#6B6560',
  border:       '#E5DED5',
  link:         '#B07D62',      // terracotta accent
  btnDisabled:  '#C5BDB6',
};

// ── Splash screen ─────────────────────────────────────────────────────────────

export const splashColors = {
  bg:       '#C8A9A4',   // mid-point of landing gradient
  text:     '#FFFFFF',
  textSub:  'rgba(255, 255, 255, 0.75)',
};

// ── Gradients ─────────────────────────────────────────────────────────────────
// Used by LinearGradient on the landing page and background component.

export const gradients = {
  background: ['#DDD0C4', '#C8A9A4', '#A87A74', '#6b3e38'] as const,
  backgroundShort: ['#DDD0C4', '#C8A9A4', '#A87A74'] as const,  // 3-stop for Background component
};

// ── Typography ────────────────────────────────────────────────────────────────

export const fonts = {
  primary:  'LexendDeca',
  fallback: 'System',
};
