// Design tokens — single source of truth for all visual values in the app.
//
// FUTURE: this file will be auto-generated by the design token pipeline.
// When that happens, edit tokens/tokens.json and run:
//   node scripts/build-tokens.js
// That script will overwrite this file — do not edit manually after that point.
//
// Until then, all design value changes go here.

// ── Colours ───────────────────────────────────────────────────────────────
// Matches the CSS variables in services/frontend/static/css/theme.css

export const colors = {
  // Core palette
  primary:     '#A87A74',
  text:        '#2D1E1C',
  textMuted:   '#6B4E4B',
  textLight:   '#A89290',

  // Backgrounds
  bgBase:      '#DDD0C4',
  bgGlass:     'rgba(241, 227, 211, 0.60)',
  bgGlassStrong: 'rgba(241, 227, 211, 0.80)',
  bgWarm:      'rgba(241, 227, 211, 0.95)',    // warm off-white — top bar text/icons on gradient bg

  // Borders
  border:        'rgba(168, 122, 116, 0.28)',
  borderCard:    'rgba(168, 122, 116, 0.22)',  // card border — matches website auth.css
  borderFocus:   'rgba(168, 122, 116, 0.55)',  // input focus state
  borderError:   'rgba(192, 57, 43, 0.30)',
  borderSuccess: 'rgba(39, 127, 82, 0.30)',

  // Input
  inputBg:     'rgba(241, 227, 211, 0.55)',    // matches website .form-group input background

  // Button — matches website .auth-form .btn-primary
  btnPrimary:        '#2D1E1C',                      // default: dark brown
  btnPrimaryPressC1: '#C9A29D',                      // pressed gradient start — matches website hover
  btnPrimaryPressC2: '#A87A74',                      // pressed gradient end

  // Semantic
  error:       '#A0291C',
  errorBg:     'rgba(192, 57, 43, 0.08)',
  success:     '#1E6B44',
  successBg:   'rgba(39, 127, 82, 0.08)',
  white:       '#FFFFFF',
};

// Dark mode — clean dark theme, same app just dark.
// Near-black bg with a very subtle warm tint, terracotta accent kept, white text.
export const darkColors = {
  primary:     '#C8A9A4',                         // terracotta accent — slightly lighter for dark bg

  text:        'rgba(255, 255, 255, 0.90)',
  textMuted:   'rgba(255, 255, 255, 0.55)',
  textLight:   'rgba(255, 255, 255, 0.35)',

  bgBase:      '#1C1917',                          // near-black with subtle warm tint
  bgGlass:     'rgba(40, 34, 32, 0.85)',           // bubble / card bg
  bgGlassStrong: 'rgba(28, 24, 22, 0.97)',         // sidebar bg
  bgWarm:      'rgba(221, 208, 196, 0.95)',

  border:        'rgba(255, 255, 255, 0.10)',
  borderCard:    'rgba(255, 255, 255, 0.08)',
  borderFocus:   'rgba(200, 169, 164, 0.50)',
  borderError:   'rgba(224, 112, 96, 0.40)',
  borderSuccess: 'rgba(39, 127, 82, 0.35)',

  inputBg:     'rgba(40, 34, 32, 0.90)',

  btnPrimary:        '#C8A9A4',
  btnPrimaryPressC1: '#C9A29D',
  btnPrimaryPressC2: '#A87A74',

  error:       '#E07060',
  errorBg:     'rgba(224, 112, 96, 0.15)',
  success:     '#4CAF82',
  successBg:   'rgba(39, 127, 82, 0.15)',
  white:       '#FFFFFF',
};

// ── Gradients ─────────────────────────────────────────────────────────────
// Colour stops only — each platform applies them in its own way.
// Website: linear-gradient(145deg, ...)  App: expo-linear-gradient

export const gradients = {
  background: ['#DDD0C4', '#C8A9A4', '#A87A74', '#6b3e38'] as const,
};

// ── Typography ────────────────────────────────────────────────────────────
// Matches font-family in services/frontend/static/css/theme.css

export const fonts = {
  primary:  'LexendDeca',   // loaded via expo-google-fonts (to be set up)
  fallback: 'System',
};
